version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: zync-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5432 # Expose pg on port 5431 to not collide with pg from elsewhere
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
