name: Lint, Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Lint
        run: |
          yarn nx workspace-lint
          yarn nx format:check
          yarn nx affected --base=${{ env.NX_BASE }} --head=${{ env.NX_BASE }} --target=lint --parallel=3
      - name: Test
        run: yarn nx affected --base=${{ env.NX_BASE }} --head=${{ env.NX_BASE }} --target=test --parallel=3 --ci --code-coverage

      - name: Build
        run: yarn nx affected --base=${{ env.NX_BASE }} --head=${{ env.NX_BASE }} --target=build --parallel=3
